PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>

SELECT ?capital ?capitalLabel WHERE {
  wd:Q884 wdt:P36 ?capital .
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "ko,en" .
  }
}
