PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>

SELECT ?country ?countryLabel ?capital ?capitalLabel WHERE {
  VALUES ?country { wd:Q884 wd:Q17 wd:Q142 }
  ?country wdt:P36 ?capital .
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "ko,en" .
  }
}
